// Generated by ./gym web frontend from config/web.json. Do not edit by hand.
export const CONFIG = {
  "blockPath": "config/block.json",
  "mainBranch": "main",
  "owner": "yunusdanabas",
  "readPrefixes": [
    "config/block.json",
    "derived/web.json",
    "queue/readbacks/"
  ],
  "repo": "gym-ledger-inbox",
  "statePath": "derived/web.json",
  "uploadsEnabled": false,
  "writePrefixes": [
    "queue/confirmations/",
    "queue/submissions/"
  ]
};
